name: TelePigeon PR Builder
on:
  pull_request:
    branches: [ develop, main ]
defaults:
  run:
    shell: bash
    working-directory: .
jobs:
  build:
    name: PR Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Change gradlew permissions
        run: chmod +x ./gradlew

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Touch local properties
        run: touch local.properties

      - name: Decode google-services.json
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
        run: echo $FIREBASE_SECRET > app/google-services.json

      - name: Access BASE_URL
        env:
          HFM_BASE_URL: ${{ secrets.BASE_URL }}
        run: echo "base.url=\"$BASE_URL\"" >> local.properties

      - name: Access IO_SENTRY_DSN
        env:
          IO_SENTRY_DSN: ${{ secrets.IO_SENTRY_DSN }}
        run: echo "io.sentry.dsn=\"$IO_SENTRY_DSN\"" >> local.properties

      - name: Lint Check
        run: ./gradlew ktlintCheck -PcompileSdkVersion=34

      - name: Build with Gradle
        run: ./gradlew build -PcompileSdkVersion=34